project_id = "aytnjjteziwwbfqddjrw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.link-preview]
    verify_jwt = false

